/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5He29sGbcDJ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function interfaz() {
  return (
    <div className="max-w-sm mx-auto p-4 bg-white shadow-lg rounded-lg">
      <div className="flex flex-col space-y-4">
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="cliente">
            Cliente
          </label>
          <Select>
            <SelectTrigger id="cliente">
              <SelectValue placeholder="Fran Ramirez" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="Fran Ramirez">Fran Ramirez</SelectItem>
              <SelectItem value="Other Client">Other Client</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="operacion">
            T Operacion
          </label>
          <Select>
            <SelectTrigger id="operacion">
              <SelectValue placeholder="Compramos USD con ARS" />
            </SelectTrigger>
            <SelectContent position="popper">
              <SelectItem value="Compramos USD con ARS">Compramos USD con ARS</SelectItem>
              <SelectItem value="Vendemos USD por ARS">Vendemos USD por ARS</SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="ingreso">
            Ingreso
          </label>
          <Input id="ingreso" placeholder="500,00" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="egreso">
            Egreso
          </label>
          <Input id="egreso" placeholder="0,00" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="cotizacion">
            Cotizacion
          </label>
          <Input id="cotizacion" placeholder="Enter value" />
        </div>
        <div>
          <label className="block text-sm font-medium text-gray-700" htmlFor="comment">
            Coment
          </label>
          <Textarea id="comment" placeholder="Add a comment" />
        </div>
        <Button className="w-20 h-20 rounded-full bg-green-500 text-white text-2xl shadow-lg">GO!</Button>
      </div>
    </div>
  )
}
